"""add_email_verified_and_token_tables

Revision ID: 0a8d6f04d55e
Revises: 272f87d3bfff
Create Date: 2026-04-28 23:38:22.117147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8d6f04d55e'
down_revision: Union[str, Sequence[str], None] = '272f87d3bfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_tokens_id'), 'email_verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_tokens_token'), 'email_verification_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_email_verification_tokens_user_id'), 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.add_column('accounts', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('created_by', sa.String(), nullable=True))
    op.add_column('accounts', sa.Column('pipeline_stage', sa.String(), nullable=False))
    op.add_column('accounts', sa.Column('pipeline_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('accounts', sa.Column('last_auto_followup_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_accounts_created_by'), 'accounts', ['created_by'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'accounts', 'tenants', ['tenant_id'], ['id'])
    op.add_column('amazon_credentials', sa.Column('ship_from_json', sa.Text(), nullable=True))
    op.add_column('contacts', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('created_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_contacts_created_by'), 'contacts', ['created_by'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'contacts', 'tenants', ['tenant_id'], ['id'])
    op.add_column('follow_ups', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('follow_ups', sa.Column('created_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_follow_ups_created_by'), 'follow_ups', ['created_by'], unique=False)
    op.create_index(op.f('ix_follow_ups_tenant_id'), 'follow_ups', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'follow_ups', 'tenants', ['tenant_id'], ['id'])
    op.add_column('orders', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('created_by', sa.String(), nullable=True))
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_orders_created_by'), 'orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'tenants', ['tenant_id'], ['id'])
    op.add_column('products', sa.Column('buy_box_winner', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('buy_box_checked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_products_seller_sku'), 'products', ['seller_sku'], unique=False)
    op.add_column('repricer_strategies', sa.Column('min_roi', sa.Float(), nullable=True))
    op.add_column('repricer_strategies', sa.Column('aggressiveness', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notify_email', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('dashboard_sections', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('page_permissions', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.drop_column('users', 'page_permissions')
    op.drop_column('users', 'dashboard_sections')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'notify_email')
    op.drop_column('users', 'email')
    op.drop_column('users', 'tenant_id')
    op.drop_column('repricer_strategies', 'aggressiveness')
    op.drop_column('repricer_strategies', 'min_roi')
    op.drop_index(op.f('ix_products_seller_sku'), table_name='products')
    op.drop_column('products', 'buy_box_checked_at')
    op.drop_column('products', 'buy_box_winner')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_by'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=1)
    op.drop_column('orders', 'created_by')
    op.drop_column('orders', 'tenant_id')
    op.drop_constraint(None, 'follow_ups', type_='foreignkey')
    op.drop_index(op.f('ix_follow_ups_tenant_id'), table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_created_by'), table_name='follow_ups')
    op.drop_column('follow_ups', 'created_by')
    op.drop_column('follow_ups', 'tenant_id')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_by'), table_name='contacts')
    op.drop_column('contacts', 'created_by')
    op.drop_column('contacts', 'tenant_id')
    op.drop_column('amazon_credentials', 'ship_from_json')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_created_by'), table_name='accounts')
    op.drop_column('accounts', 'last_auto_followup_at')
    op.drop_column('accounts', 'pipeline_updated_at')
    op.drop_column('accounts', 'pipeline_stage')
    op.drop_column('accounts', 'created_by')
    op.drop_column('accounts', 'tenant_id')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_user_id'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_token'), table_name='email_verification_tokens')
    op.drop_index(op.f('ix_email_verification_tokens_id'), table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    # ### end Alembic commands ###
